### ISSUE TITLE
[v1.1.0] Compilation errors on Unity 2021.3 due to GraphicsBuffer APIs unavailable before Unity 2022.2

### ISSUE THREAD

**Issue by LeoChen125** [harumas/UGizmo#11]
## Summary

After upgrading from v1.0.1 to v1.1.0, the package fails to compile on Unity 2021.3 LTS. 
The `package.json` declares `"unity": "2021.3"` as the minimum version, but the code 
in `GizmoDrawBuffer.cs` uses `GraphicsBuffer` APIs that were only introduced in Unity 2022.2.

## Environment

- Unity version: 2021.3.x (LTS)
- UGizmo version: 1.1.0
- Previously working version: 1.0.1

## Errors

GizmoDrawBuffer.cs(41,98): error CS0117: 'GraphicsBuffer' does not contain a definition for 'UsageFlags'
GizmoDrawBuffer.cs(41,34): error CS1729: 'GraphicsBuffer' does not contain a constructor that takes 4 arguments
GizmoDrawBuffer.cs(95,62): error CS1061: 'GraphicsBuffer' does not contain a definition for 'LockBufferForWrite'
GizmoDrawBuffer.cs(100,28): error CS1061: 'GraphicsBuffer' does not contain a definition for 'UnlockBufferAfterWrite'

## Root Cause

`GizmoDrawBuffer.cs` line 41 uses the following APIs that were added in **Unity 2022.2**:

- `GraphicsBuffer.UsageFlags.LockBufferForWrite` 
- `new GraphicsBuffer(Target, UsageFlags, count, stride)` (4-argument constructor)
- `GraphicsBuffer.LockBufferForWrite<T>()`
- `GraphicsBuffer.UnlockBufferAfterWrite<T>()`

Reference: https://docs.unity3d.com/2022.2/Documentation/ScriptReference/GraphicsBuffer.UsageFlags.html

## Expected Behavior

The package should compile on Unity 2021.3 as declared in `package.json`, matching the 
behavior of v1.0.1. Either:
1. Update the minimum Unity version in `package.json` to `2022.2`, or
2. Provide a fallback code path for Unity 2021.x (e.g., using `SetData` instead of `LockBufferForWrite`)

## Workaround

Downgrade to v1.0.1.
